name: Lint and format

on: [push, pull_request, merge_group]

jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: |
          npm install -g pnpm
          pnpm install
          pnpm run check_style
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: |
          npm install -g pnpm
          pnpm install
          pnpm run lint
